---
title: "DTW-Vergleich"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(ggplot2)
library(dplyr)
library(reshape2)
library(psych)
```

```{r readfiles}
df.120.DTW = read.csv(file=file.path("..","120Hz","Dtw","output","auswertung1.csv"), sep=";")
df.120.FDTW = read.csv(file=file.path("..","120Hz","Fastdtw","output","auswertung1.csv"), sep=";")
df.500.FDTW = read.csv(file=file.path("..","500Hz","Fastdtw","output","auswertung1_1-13(o6)_neu.csv"), sep=";")
```

```{r preprocess}
m.labels = function(df){
  df <- df %>% mutate(Block = case_when(grepl("Spot", Video) ~ "Spot",
                                      grepl("BGL", Video) ~ "CL",
                                      grepl("GL", Video) ~ "SL",
                                      grepl("Control", Video) ~ "Kontrolle",
                                      TRUE ~ "none"))
  df$Block.f <- as.factor(df$Block)
  df$Block.f <- factor(df$Block.f, levels = c("Kontrolle", "Spot", "SL", "CL"))
  
  df$PB <- gsub("pb", "", df$Proband)
  df$PB <- as.numeric(df$PB)
  
  df <- df %>% mutate(speed = case_when((PB %% 2) == 0 ~ "langsam", TRUE ~ "schnell") )
  df$speed.f <- as.factor(df$speed)
  
  return(df)
}
df.120.DTW = m.labels(df.120.DTW)
df.120.FDTW = m.labels(df.120.FDTW)
df.500.FDTW = m.labels(df.500.FDTW)

sp.120.DTW = subset(df.120.DTW, Block.f != "Kontrolle")
sp.120.FDTW = subset(df.120.FDTW,Block.f != "Kontrolle")
sp.500.FDTW = subset(df.500.FDTW,Block.f != "Kontrolle")
```

```{r korrektur/skalierung}
factor = 120/500
# total _distance
sp.120.DTW <- sp.120.DTW %>% mutate(total_distance = case_when((PB %% 2)==0 ~ total_distance/2, TRUE ~ total_distance))
sp.120.FDTW <- sp.120.FDTW %>% mutate(total_distance = case_when((PB %% 2)==0 ~ total_distance/2, TRUE ~ total_distance))
sp.500.FDTW <- sp.500.FDTW  %>% mutate(total_distance = case_when((PB %% 2)==0 ~ factor * total_distance/2, TRUE ~factor * total_distance))

# mean distance - no correct

# median distance - no correct

#zero.overhead.counter
sp.120.DTW <- sp.120.DTW %>% mutate(zero.overhead.counter = as.integer(case_when((PB %% 2)==0 ~ as.double(zero.overhead.counter)/2, TRUE ~ as.double(zero.overhead.counter))))
sp.120.FDTW <- sp.120.FDTW %>% mutate(zero.overhead.counter = as.integer(case_when((PB %% 2)==0 ~ as.double(zero.overhead.counter)/2, TRUE ~ as.double(zero.overhead.counter))))
sp.500.FDTW <- sp.500.FDTW  %>% mutate(zero.overhead.counter = as.integer(case_when((PB %% 2)==0 ~ factor * as.double(zero.overhead.counter)/2, TRUE ~factor * as.double(zero.overhead.counter))))

#ref.before.query..rbq.
sp.120.DTW <- sp.120.DTW %>% mutate(ref.before.query..rbq. = as.integer(case_when((PB %% 2)==0 ~ as.double(ref.before.query..rbq.)/2, TRUE ~ as.double(ref.before.query..rbq.))))
sp.120.FDTW <- sp.120.FDTW %>% mutate(ref.before.query..rbq. = as.integer(case_when((PB %% 2)==0 ~ as.double(ref.before.query..rbq.)/2, TRUE ~ as.double(ref.before.query..rbq.))))
sp.500.FDTW <- sp.500.FDTW  %>% mutate(ref.before.query..rbq. = as.integer(case_when((PB %% 2)==0 ~ factor * as.double(ref.before.query..rbq.)/2, TRUE ~factor * as.double(ref.before.query..rbq.))))

#query.before.ref..bqr.
sp.120.DTW <- sp.120.DTW %>% mutate(query.before.ref..qbr. = as.integer(case_when((PB %% 2)==0 ~ as.double(query.before.ref..qbr.)/2, TRUE ~ as.double(query.before.ref..qbr.))))
sp.120.FDTW <- sp.120.FDTW %>% mutate(query.before.ref..qbr. = as.integer(case_when((PB %% 2)==0 ~ as.double(query.before.ref..qbr.)/2, TRUE ~ as.double(query.before.ref..qbr.))))
sp.500.FDTW <- sp.500.FDTW  %>% mutate(query.before.ref..qbr. = as.integer(case_when((PB %% 2)==0 ~ factor * as.double(query.before.ref..qbr.)/2, TRUE ~factor * as.double(query.before.ref..qbr.))))
```


```{r plot funcs}
boxplot1 = function(df,name){
  for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    #desk <- by(df.sub$total_distance, list(df.sub$Block.f, df.sub$speed.f), describe)
    filename = paste0(name,"_",distance,"_","boxplot_total_distance.jpeg")
    print(filename)
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=total_distance, x= Block.f, color = speed.f)) + geom_boxplot() + 
    labs(x = "Visualisierung", y = "Distanz gesamt", color = "Geschwindigkeit",title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
  }
}
boxplot2 = function(df,name){
  for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    #desk <- by(df.sub$total_distance, list(df.sub$Block.f, df.sub$speed.f), describe)
    filename = paste0(name,"_",distance,"_","boxplot_mean_distance.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=mean_distance, x= Block.f, color = speed.f)) + geom_boxplot() + 
    labs(x = "Visualisierung", y = "Distanz Mittelwert", color = "Geschwindigkeit",title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
  }
}
boxplot3 = function(df,name){
  for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    #desk <- by(df.sub$total_distance, list(df.sub$Block.f, df.sub$speed.f), describe)
    filename = paste0(name,"_",distance,"_","boxplot_median_distance.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=median_distance, x= Block.f, color = speed.f)) + geom_boxplot() + 
    labs(x = "Visualisierung", y = "Distanz Median", color = "Geschwindigkeit",title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
  }
}
boxplot1(sp.120.DTW,"DTW_120Hz")
boxplot1(sp.120.FDTW,"FDTW_120Hz")
boxplot1(sp.500.FDTW,"FDTW_500Hz")

boxplot2(sp.120.DTW,"DTW_120Hz")
boxplot2(sp.120.FDTW,"FDTW_120Hz")
boxplot2(sp.500.FDTW,"FDTW_500Hz")

boxplot3(sp.120.DTW,"DTW_120Hz")
boxplot3(sp.120.FDTW,"FDTW_120Hz")
boxplot3(sp.500.FDTW,"FDTW_500Hz")
``` 
```{r plot funcs2}
boxplot1.2 = function(df,name){
  for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_total_distance_trials.jpeg")
    print(filename)
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=total_distance, x= Video, color = speed.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
  }
}
boxplot2.2 = function(df,name){
  for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_mean_distance_trials.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=mean_distance, x= Video, color = speed.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
  }
}
boxplot3.2 = function(df,name){
  for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_median_distance_trials.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=median_distance, x= Video, color = speed.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
  }
}
boxplot1.2(sp.120.DTW,"DTW_120Hz")
boxplot1.2(sp.120.FDTW,"FDTW_120Hz")
boxplot1.2(sp.500.FDTW,"FDTW_500Hz")

boxplot2.2(sp.120.DTW,"DTW_120Hz")
boxplot2.2(sp.120.FDTW,"FDTW_120Hz")
boxplot2.2(sp.500.FDTW,"FDTW_500Hz")

boxplot3.2(sp.120.DTW,"DTW_120Hz")
boxplot3.2(sp.120.FDTW,"FDTW_120Hz")
boxplot3.2(sp.500.FDTW,"FDTW_500Hz")
``` 

```{r boxplot}
boxplot4 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_no_overhead.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=zero.overhead.counter, x= Block.f, color = speed.f)) + geom_boxplot() + 
    labs(x = "Visualisierung", y = "Anzahl ohne Versatz", title = paste0("Distanz : ",distance), color = "Geschwindigkeit")
    print(myplot)
    dev.off()
   }
}
boxplot5 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_plus_overhead.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=ref.before.query..rbq., x= Block.f, color = speed.f)) + geom_boxplot() +
    labs(x = "Visualisierung", y = "Anzahl Blick hinter Visualisierung", title = paste0("Distanz : ",distance), color = "Geschwindigkeit")
    print(myplot)
    dev.off()
   }
}
boxplot6 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_minus_overhead.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=query.before.ref..qbr., x= Block.f, color = speed.f)) + geom_boxplot() + 
    labs(x = "Visualisierung", y = "Anzahl Blick vor Visualisierung", title = paste0("Distanz : ",distance), color = "Geschwindigkeit")
    print(myplot)
    dev.off()
   }
}
boxplot4(sp.120.DTW,"DTW_120Hz")
boxplot4(sp.120.FDTW,"FDTW_120Hz")


boxplot5(sp.120.DTW,"DTW_120Hz")
boxplot5(sp.120.FDTW,"FDTW_120Hz")

boxplot6(sp.500.FDTW,"FDTW_500Hz")
boxplot6(sp.120.DTW,"DTW_120Hz")

#sollte wieder gehen 
boxplot5(sp.500.FDTW,"FDTW_500Hz")
boxplot4(sp.500.FDTW,"FDTW_500Hz")
boxplot6(sp.120.FDTW,"FDTW_120Hz")

```

```{r boxplot2}
boxplot4.2 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_no_overhead_trials.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=zero.overhead.counter, x= Video, color = speed.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
boxplot5.2 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_plus_overhead_trials.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=ref.before.query..rbq., x= Video, color = speed.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
boxplot6.2 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","boxplot_minus_overhead_trials.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=query.before.ref..qbr., x= Video, color = speed.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
boxplot4.2(sp.120.DTW,"DTW_120Hz")
boxplot4.2(sp.120.FDTW,"FDTW_120Hz")
boxplot4.2(sp.500.FDTW,"FDTW_500Hz")

boxplot5.2(sp.120.DTW,"DTW_120Hz")
boxplot5.2(sp.120.FDTW,"FDTW_120Hz")
boxplot5.2(sp.500.FDTW,"FDTW_500Hz")

boxplot6.2(sp.120.DTW,"DTW_120Hz")
boxplot6.2(sp.120.FDTW,"FDTW_120Hz")
boxplot6.2(sp.500.FDTW,"FDTW_500Hz")
```

```{r plots3}
maxrbq.plot1 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","maxrbq_1.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=max.rbq, x= Block.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
maxrbq.plot2 = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","maxrbq_2.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=max.rbq, x= Video)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
maxqbr.plot1  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","maxqbr_1.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=max.qbr, x= Block.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
maxqbr.plot2  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","maxqbr_2.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=max.qbr, x= Video)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
maxdistance.plot1  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","maxdistance_1.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=max.distance, x= Block.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
maxdistance.plot2  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","maxdistance_2.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=max.distance, x= Video)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
mindistance.plot1  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","mindistance_1.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=min.distance, x= Block.f)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}
mindistance.plot2  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    filename = paste0(name,"_",distance,"_","mindistance_2.jpeg")
    jpeg(filename = filename,units="in",width=5,height=5,res=300)
    myplot <- ggplot(df.sub, aes(y=min.distance, x= Video)) + geom_boxplot() + labs(title = paste0("Distanz : ",distance))
    print(myplot)
    dev.off()
   }
}

maxqbr.plot1(sp.120.DTW,"DTW_120Hz")
maxqbr.plot1(sp.120.FDTW,"FDTW_120Hz")
maxqbr.plot1(sp.500.FDTW,"FDTW_500Hz")

maxqbr.plot2(sp.120.DTW,"DTW_120Hz")
maxqbr.plot2(sp.120.FDTW,"FDTW_120Hz")
maxqbr.plot2(sp.500.FDTW,"FDTW_500Hz")

maxrbq.plot1(sp.120.DTW,"DTW_120Hz")
maxrbq.plot1(sp.120.FDTW,"FDTW_120Hz")
maxrbq.plot1(sp.500.FDTW,"FDTW_500Hz")

maxrbq.plot2(sp.120.DTW,"DTW_120Hz")
maxrbq.plot2(sp.120.FDTW,"FDTW_120Hz")
maxrbq.plot2(sp.500.FDTW,"FDTW_500Hz")

maxdistance.plot1(sp.120.DTW,"DTW_120Hz")
maxdistance.plot1(sp.120.FDTW,"FDTW_120Hz")
maxdistance.plot1(sp.500.FDTW,"FDTW_500Hz")

maxdistance.plot2(sp.120.DTW,"DTW_120Hz")
maxdistance.plot2(sp.120.FDTW,"FDTW_120Hz")
maxdistance.plot2(sp.500.FDTW,"FDTW_500Hz")

mindistance.plot1(sp.120.DTW,"DTW_120Hz")
mindistance.plot1(sp.120.FDTW,"FDTW_120Hz")
mindistance.plot1(sp.500.FDTW,"FDTW_500Hz")

mindistance.plot2(sp.120.DTW,"DTW_120Hz")
mindistance.plot2(sp.120.FDTW,"FDTW_120Hz")
mindistance.plot2(sp.500.FDTW,"FDTW_500Hz")

```

```{r plots4}

    
    
histogramm.bins.plot_1  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
    df.sub = subset(df,Distancemeasure == distance)
    names(df.sub)[16:220]<-c(-102:102)
    df.sub.t = df.sub[,-c(16:93,143:220)]
    df.sub.h <- subset(df.sub.t, select = -c(Video, IP, Distancemeasure, total_distance, len_of_signal, mean_distance, median_distance, zero.overhead.counter, ref.before.query..rbq., query.before.ref..qbr., max.rbq, max.qbr, max.distance, min.distance, Block, speed, PB))
    df.sub.hm <- melt(df.sub.h, id.vars=c("Proband", "speed.f", "Block.f"))
colnames(df.sub.hm)[colnames(df.sub.hm)=="variable"] <- "bin"
    barplot.eu <- df.sub.hm %>% group_by(Block.f,bin) %>% summarise(mw= mean(value), sd = sd(value, na.rm = T), median = median(value))
    filename = paste0(name,"_",distance,"_","histogramm_bins_mw_häufigkeit.jpeg")
    jpeg(filename = filename,units="in",width=11,height=8,res=300)
    p<- ggplot(barplot.eu, aes(x=bin, y=mw, fill = Block.f)) + geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=mw-sd, ymax=mw+sd), width=.2, position=position_dodge(.9))  + labs(title = paste0("Distanz : ",distance))
    print(p)
    dev.off()
   }
}

histogramm.bins.plot_2  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
     df.sub = subset(df,Distancemeasure == distance)
    names(df.sub)[16:220]<-c(-102:102)
    df.sub.t = df.sub[,-c(16:93,143:220)]
    df.sub.h <- subset(df.sub.t, select = -c(Video, IP, Distancemeasure, total_distance, len_of_signal, mean_distance, median_distance, zero.overhead.counter, ref.before.query..rbq., query.before.ref..qbr., max.rbq, max.qbr, max.distance, min.distance, Block, speed, PB))
    df.sub.hm <- melt(df.sub.h, id.vars=c("Proband", "speed.f", "Block.f"))
colnames(df.sub.hm)[colnames(df.sub.hm)=="variable"] <- "bin"
    barplot.eu <- df.sub.hm %>% group_by(Block.f,bin) %>% summarise(mw= mean(value), sd = sd(value, na.rm = T), median = median(value))
    filename = paste0(name,"_",distance,"_","histogramm_bins_median_häufigkeit.jpeg")
    jpeg(filename = filename,units="in",width=11,height=8,res=300)
    q<- ggplot(barplot.eu, aes(x=bin, y=median, fill = Block.f)) + geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=mw-sd, ymax=mw+sd), width=.2, position=position_dodge(.9))  + labs(title = paste0("Distanz : ",distance))
    print(q)
    dev.off()
   }
}

histogramm.bins.plot_3  = function(df,name){
   for (distance in c("euklid","winkel","winkellog")){
     df.sub = subset(df,Distancemeasure == distance)
    names(df.sub)[16:220]<-c(-102:102)
    df.sub.t = df.sub[,-c(16:93,143:220)]
    df.sub.h <- subset(df.sub.t, select = -c(Video, IP, Distancemeasure, total_distance, len_of_signal, mean_distance, median_distance, zero.overhead.counter, ref.before.query..rbq., query.before.ref..qbr., max.rbq, max.qbr, max.distance, min.distance, Block, speed, PB))
    df.sub.hm <- melt(df.sub.h, id.vars=c("Proband", "speed.f", "Block.f"))
colnames(df.sub.hm)[colnames(df.sub.hm)=="variable"] <- "bin"
    
    
    barplot.eu <- df.sub.hm %>% group_by(Block.f,bin) %>% summarise(mw= mean(value), sd = sd(value, na.rm = T), median = median(value))
    filename = paste0(name,"_",distance,"_","histogramm_bins_häufigkeit.jpeg")
    jpeg(filename = filename,units="in",width=11,height=8,res=300)
    r<- ggplot(df.sub.hm, aes(x=bin, y=value, fill = Block.f)) + geom_boxplot() + facet_wrap(~ speed.f) +labs(title = paste0("Distanz : ",distance))
    print(r)
    dev.off()
   }
}



    

histogramm.bins.plot_1(sp.120.DTW,"DTW_120Hz")
histogramm.bins.plot_1(sp.120.FDTW,"FDTW_120Hz")
histogramm.bins.plot_1(sp.500.FDTW,"FDTW_500Hz")

histogramm.bins.plot_2(sp.120.DTW,"DTW_120Hz")
histogramm.bins.plot_2(sp.120.FDTW,"FDTW_120Hz")
histogramm.bins.plot_2(sp.500.FDTW,"FDTW_500Hz")

histogramm.bins.plot_3(sp.120.DTW,"DTW_120Hz")
histogramm.bins.plot_3(sp.120.FDTW,"FDTW_120Hz")
histogramm.bins.plot_3(sp.500.FDTW,"FDTW_500Hz")


```









